### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rexdotsh** [davrashop/JioCinema-4K-Tool-Non-DRM#1]
.

**Comment by rexiscodin** [comment]
oh nevermind i fixed this by installing python 3.9.0b5, but now another error
![Capture](https://user-images.githubusercontent.com/65942753/173526308-e7a8699e-37a7-4012-af07-5ad653234d77.PNG)

**Comment by rexiscodin** [comment]
figured it out, had to use watch url instead of that one
